language: java

jdk:
- oraclejdk8

before_install:
- sudo apt-get update -qq
- sudo apt-get install oracle-java8-installer
- chmod +x ./gradlew
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

install:
- java -Xmx32m -version
- "./gradlew --daemon --info compileJava compileTestJava"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_script:
- chmod +x ./cd/init-display.sh
- "./cd/init-display.sh"

script:
- "./gradlew --daemon check"

after_success:
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
- "./cd/before-deploy.sh"
- ./gradlew --daemon assemble
- "./cd/deploy.sh"

env:
  global:
    - secure: "liNJLBfTUKsBr8wgAZ+Mzdy/SKekz3BIiCQq2lw4DuZMBXPvO8LNPG0NFpAD0ZWKBjlRmWlGrujvSek/3c3kDKx4pl9afEDM1qnV/G8M5ehY/ZJwkQPvVLdVXnCgwRgiTUBw8+jaiHfrArqdumEDh5QYpDtOM8QY8gzFIXFah+Vm6AfJNo/MM5Nf/EZHLzrfjh0Elfm/Qt3YXNsI6S4RcjKASRPauU9iTm6kgUx/MEaP9Mb5lv1XZMH3sT4XdQLM0cFNy9dV1Knk4sZClcdEGNJYpERDA4CoN41ep5euOUpR7IO85KlaPEICaQZG9FUz/pLqDES3Gq+3q+zS9pu68Wx2/c4IKnaGfM3mwBKgo3HKAF9/OI2pgYbkQoiIYXNzSrcw249XgsROUZXEEkTbsLVAVQ4tNECyZIakXAJfg7TVwxS+ckYr/gny/MnCn0iJJ6DTDcqfAFefJkPhQRO4QXch6z3nowrv//rw0kgCgIcnxpJIMYRRFtMeAfkly5tpDR6z9292FZBiilqm/ZaM3cvph+uEdTcQo91ZQWYnprYTit1q6Xw2MKdEdGDxmbgzr7rKAGz6ESgt7kfptYscyg4GEytCJtlDI4+HvFGI/i96dboUz3wgX5r524Z6o8Oy6xwm9r4l8y99hKA1a6PcxexU/jyYsGKm/Q/vSSN5QC0="
    - secure: "WV6XOnPQbbRa9F5XZ5aUp/zQuVUd9eyX2SnTZIW9TBb3KhHra5W3NboNoPfh+g6dfOGklrl+/8P4zTRbkbui1FeuFSQmwdmNv/dfMkAjqmzQykNJCGKRkIOz0lpIqdL4vYeItU4pjRQWPxCOu7ydlTat9FmX+/frPVDxlJlVEjSRSpEtd0dBKhlLNvgdx0folvX2MHM0CTGfdFbBMkkUcuw1+ODg03iKiN0Sb5k/53GsAocgI6d6koG2GjRvaMYOQ+pAtXyxZL9MH3sCmy5RPuqu1cLWgSizJTPny02FcFMLDGZ2eWUXhExugOM13ac+jFgX4oHSEkUT+1kmtaK9Z+R+qm+8mWKu+D8oBxIGccpffpQZfSPyGvbAus4mUIXMJQOTVtRBMZ0w7/QutrPfXGakMAAJcZfLWeUmi+frFg4ClZuFG+vkUZncNVSfr4NWXmULFhDZFyl3FWDYUIG75D6FaTc/TO4FkIJuLaMcoZ0SoJSKuZ001EEeJED8M7zVIOt5RIrMncZN5VeqrGVyEKQR7DEi6ObDWyBzBA+wYnZnHHJo/ourMLCo26uywJ6LHpmuA2VJ/rnXpqo6kZEWmk3I/1uVzLX796gJIkNsx+szv/aS5oTYG4X5cVIlBM99glfH0pDgWbYWkXy0/2//MgPNa01MSj0Xb1xB3PRymC0="
    - secure: "lkeG8rr6NI4H0gvMObtvpFP0DzOtpsjxdWAptCnA2AJ/VgzTNwhP353KrHysxsK/kwEjg49xyfS1zYZHv/la2zrZy02zBfcNROR9I7oKeXhy36oqt22mQgYvEYu3qhJc6jFcU8H36x5N+a8uCwr/vS3OXoJdLbFOqz4URFYJE6AHngS9dxllEz5qmjf9KxLN1Q7EG1xXLbnN1KsWW73+8Xo0SaGlO1RZlq8X6rieOj32EOqPfyjVJ3k6yHKDIVfNJADG6OPLCsPzUkazzryQAdksc6PWiZ/hZPsfefmzOo+CUfRA/3IGSsRKqZSSyuhywsEf9SFgD5nZ6ccd9kM87bUTTpadbjD8wtwBmOSgYe4A5mMOghdfMKLUhnvqoR1zdt6JBZrIWyjQcBusDTaUh5M6KT3beA14wFVegCRdxVgxOkijLA98RQ663r86DGgyKJ+dvS+kCNKCALtOHU1CCjiZx+RFz69EpUM6kFzc6sAzNsJyPKcMVkf5s/cXJdkHUWqWMh9N7KIWPFVA5ujaO77ZJgF+SH/BNEPHjJ0T3b3VQBP6dCJvwj297iWaJIq6eWph7T86ZWyCA1k0uub4eiuqy6kPmrU73EPntmSVAEf6OW8mtQO4FgWZEx21JW+xhCZBIHeSxqdaoUjhr1eSbeJ/tCsj8IrRw+S6ddMqaY8="
    - secure: "fXIlIEtzP/A3wpboqvZjH142YYcTt50IvuHpvnxutFajUwzwbDN5iUS7hlTzZHact1JpIMOYUkADHtdyujdUjptl6wcoZMkJG5IL4CTa8vcA0eAlxirtH0+wYykFSECzsb4V7EaBsQ5bPEKaAHjjv9s6g8kZtOR3eTbXmFg1zXTesZDCnn9bPM/lgQ1hsH4lw9mgvjXIyHVNPCeyqwPayYEgRpmlLjS/Mm1rtu4tik3HTrFkz5J08Ce+cIblllZ2JJ6IEU+IDyK4Bxtn0WHLmLgsHjZ1gPvyUfYl+ApNNIU4+Lc1TEouByq5x/0Ustt1Dpj+mpQXdWUCCAZuUsONfP3La+eRLd54pPv3tWWkuqo5Be065EMdZpxmEFdaaSOReRv5bHfgg+JBi1lRApghIgx3tmH2zukKoIYpUsJH6Aj7BAOonKb0LWe1HqF8dhYMUYJWo6yv7Hut5KuBxq1D3EIEmOarfFvWIsZ9J4GNNPgCjpIisNEY9lvzEAvoh2z7iOM7OrzgeWw4diKcuuV266eEiEi/fA4HjWRSXc+dhVCdzx+wQAgI+v0QFIe4pEBFcdipCuE3wv2vMK2+6jzIAAFl7ozxeq/FpcPWDUZ2EAE/jfPNeLUbN1YStLyhP6+hw9OKhAgD+P6B4ukD/st9QSwOQ1pBt7hNC9o3eGLb/gE="
    
