language: java

jdk:
- oraclejdk8

before_install:
- chmod +x ./gradlew
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

install:
- "./gradlew --daemon --info compileJava compileTestJava"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_script:
- chmod +x ./cd/init-display.sh
- "./cd/init-display.sh"

script:
- "./gradlew --daemon check --info"

after_success:
- jdk_switcher use oraclejdk7
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"

env:
  global:
  - secure: h4ryuoonOamJSuwdCI+SB0xg8FuOLjPelwhjKD40Ia+3QII4mM/1ko8nWg4PVtZAkLbdvopfhs/OuyxdPmkNCoI7stmfIHU58lUgohUt7P12lo1bE8X6DabYrOglct5sZlOcL44F8elNTmDigfM1Y+fsuZh1eKEdlx0Ho6lW9dDCL1rNsmHqggY/Q7+2xI+06NwxJwpW4lSDDQHPGUfWpwMBeDp5tYE8/pK7bZWNUzqEQB7UD0rr+4xwG3EI1WTsNW8KdGp5c+zGIvXIn2WzeIjOXiS+ji5Wk+Xp8Rl/8nz6AAbEbKm0PXRdts78/wRlCxtVAqrDmidZFOcQHa9qnfBq9xg841bz23Xbx8Mq/QrLDncO8wCdACh7hduMdPmKvWFOIBFQt57C+NvrlkjohImLJA2lutIf1t/MnHVDgwPz1Bq/2Ksr3rVS1wybbaejnA+B7nf5RBsccHyp0nr8Npmy1XXjnJEwMZvziHreOpV0J4QvMyshDADtVC0RLYFJVj474CLao3d+GoJtf34qkSMVLLuWsAJwIml45rc1n+fbFPU1SY+01C73RASvslqVpm6wa2/YMIIbIvDzT/vIXCOKgFiAy85NdcawrkjQp2RIiSitj4xB+sYu5Rjr1vq8xmrCNRpTGdnPZErtXuFOBiOAPCvXkRkzXMuJeoobX8c=
  - secure: LvIjXLptaKqe3TOQyyL8mGlIGaVoKs339gELv/bjFFCyWXjZbNpBWE/uCkyzzBQ5Uvs/ZGDEzdjU4V2Wm3qP5SfFQgb8IJ9/XnstTUQAucZVB/Ffbr2xTprxUPAXxHWniHfgaZnBC/AGf8Jm4Kna3VTsO+2v0986otbBAnk9oUcOQhQZIcRc1gua/qRsjpNP7BlDuTNd6kuH7V7M3LC00h5aCRJiqc6AoPgXAqrXaVl4zt0Th+2yH6lfBkyOEgTuEUDCqHMd7tgOGzEO64SvV5YIfeJlzqYlq5GOVAjtgcCRP0jH1gJy2H+OzKLMKC/pIF721LZCL8HC45nW5RqOk3MNUcyQFOxxboKKwsRQ+w93y4e+JUl1EcHTtAO01g9kgVkO7TQ85XPODEG0Tun8yEQzWohQGkZsTcpi7pUZUKwnroBfrZAGQ/M1abDGWNsE68DpG7CNdKe5wzxboYbPnG52x9Ol1k2d6poNo7NzZ4/3igc7/gGZWEgzL97Jqc6PldoqYoZNdZmA81X+PYLXAlk6WmSm1mbQYzrDx24an6UvEf9pvG2xu9FfcP4W7F2FT25nHd6IwR7Wdn9rbw7Wbfukm+VBh6FEJtxKtqs7l6RwnsHUkBZsNZyaalxqc8R3fEQOtIGUwn7zabSoC0+r0c8aZUXIBz40JfyAzJvQzDk=
  - secure: npE22srK8UL+U5BRCq50pY1N8WhOr0k9QYNzL2WARrjG7yhEy9VBUML0a6EuZyERcCRDmfPUiPmDFkR/ccQbA0DbXgX7GKOusB0i7DynPYFqDI4SuJo4ZorBPKOKpO8ayBFVc5dq50v+NRpkuRhDpBvePNnS7NwzNO9jivK1e6w0ncZydcsIghm0uV02Lyyb+4ltEUwhThsPsgHiMYFbeTKkUYoCIQxLTaux7kmJsFrpKfP6nGnDJovvqnhdFvTgvlNRMEH/X49B5MQXBVHgVGXQdm0BmFtKg8cwaEfmscD4dN9DVD8q1/peDukYLoOzNAlS4Ui0wxLdRHycKOBiSKMIC+yDCr0RwdgXGfCc0l+QGXrQl4MY+TrCUcvTcglFwXXvIEyToG1iaZd2qCVPF/6D60cCXnlzKpk5GUTKTHWbeTaNmtHJpWBjjlpr8qToP9zU4NaS4OVmJCnMUhheB5HO1qMo22U5DgYw3F2mD/JYdpHhVauaLEbLFn02v9wrA589dgAsNCVQONVDNZJbyZgzr1IeotqMG+vL/qJTSVcdkzskFLLL7K6I2Vu+2qlhvYetSZo9AIQXv4JQbk9F1g3BkG3Zbvmve1h3a43ouPqioZ3+lZqmxkUlsHYGYWCmvRAb89BXGJ32iDgBw1zqvA9KQPVcDU04mzvRMQVDI+I=
  - secure: aa2Faq+xYx8uAxLrc31NSno2m1ttXaDMGL6xezqeDFPQ8ukSjwETlmXieizizaX4OI3HR7eWJmqQlD+jbtfLdkhk6FTaJ8LyAKn5AFYzi1cFRmVDzkJkpT6PLIzEaIlI12pIUMypmfd1xSKyMCcwZUylOYcZUH8pv+9m+2ZBXC/ycUay/uQWxQ5xnftWMAwAhW+5/ms+ngIH5rRkZhFpJaw14Bpd5C2rw6TYfQXghEuBfwB3FqNP03eKmEIb1huXKjDls3Bm8LKn2LabgXdNnS4YUgvF1ur4C8xQkDI5Mx368ALUU9gBgHd+v4SMTQV06AhZlXJqZogBgMKQ0qtQyLRVI3p5+w+/DVBzLnKZnwpvj58/B3HDGSQ5G9lR51VRYtnXMUCRW/Lc6UzwHfQOrDNx0p3xD0w4sysgqO3Bx+E2e7rS1hgXOzwlh26hkeXy/wEE0d3psP2l2o7C4J9SO6fvSpMEmwE4VxIJk4fP9QVoC3CKunH7cP2/gNnSJ/YouR4QvJIzTw4wV09p9HzebCfXf7N75xHOrCiOj2Az0KLoeAGQhUElOsauEgNqpiKukrmoYQu55hU+1ol2sgKL81b8JesMCX3zHMsoXtNiftO73+kP/xZQqXEZnCzCZshxpw1RTg7MJEul2MRsjMhQouoXyvvRFmxKcNDSQ/D7pkA=
