language: java

jdk:
- oraclejdk8

before_install:
- sudo apt-get update -qq
- sudo apt-get install oracle-java8-installer
- chmod +x ./gradlew
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

install:
- java -Xmx32m -version
- "./gradlew --daemon --info compileJava compileTestJava"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_script:
- chmod +x ./cd/init-display.sh
- "./cd/init-display.sh"

script:
- "./gradlew --daemon check --info"

after_success:
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
- "./cd/before-deploy.sh"
- ./gradlew --daemon assemble
- "./cd/deploy.sh"

env:
  global:
    - secure: "liNJLBfTUKsBr8wgAZ+Mzdy/SKekz3BIiCQq2lw4DuZMBXPvO8LNPG0NFpAD0ZWKBjlRmWlGrujvSek/3c3kDKx4pl9afEDM1qnV/G8M5ehY/ZJwkQPvVLdVXnCgwRgiTUBw8+jaiHfrArqdumEDh5QYpDtOM8QY8gzFIXFah+Vm6AfJNo/MM5Nf/EZHLzrfjh0Elfm/Qt3YXNsI6S4RcjKASRPauU9iTm6kgUx/MEaP9Mb5lv1XZMH3sT4XdQLM0cFNy9dV1Knk4sZClcdEGNJYpERDA4CoN41ep5euOUpR7IO85KlaPEICaQZG9FUz/pLqDES3Gq+3q+zS9pu68Wx2/c4IKnaGfM3mwBKgo3HKAF9/OI2pgYbkQoiIYXNzSrcw249XgsROUZXEEkTbsLVAVQ4tNECyZIakXAJfg7TVwxS+ckYr/gny/MnCn0iJJ6DTDcqfAFefJkPhQRO4QXch6z3nowrv//rw0kgCgIcnxpJIMYRRFtMeAfkly5tpDR6z9292FZBiilqm/ZaM3cvph+uEdTcQo91ZQWYnprYTit1q6Xw2MKdEdGDxmbgzr7rKAGz6ESgt7kfptYscyg4GEytCJtlDI4+HvFGI/i96dboUz3wgX5r524Z6o8Oy6xwm9r4l8y99hKA1a6PcxexU/jyYsGKm/Q/vSSN5QC0="
    - secure: "WV6XOnPQbbRa9F5XZ5aUp/zQuVUd9eyX2SnTZIW9TBb3KhHra5W3NboNoPfh+g6dfOGklrl+/8P4zTRbkbui1FeuFSQmwdmNv/dfMkAjqmzQykNJCGKRkIOz0lpIqdL4vYeItU4pjRQWPxCOu7ydlTat9FmX+/frPVDxlJlVEjSRSpEtd0dBKhlLNvgdx0folvX2MHM0CTGfdFbBMkkUcuw1+ODg03iKiN0Sb5k/53GsAocgI6d6koG2GjRvaMYOQ+pAtXyxZL9MH3sCmy5RPuqu1cLWgSizJTPny02FcFMLDGZ2eWUXhExugOM13ac+jFgX4oHSEkUT+1kmtaK9Z+R+qm+8mWKu+D8oBxIGccpffpQZfSPyGvbAus4mUIXMJQOTVtRBMZ0w7/QutrPfXGakMAAJcZfLWeUmi+frFg4ClZuFG+vkUZncNVSfr4NWXmULFhDZFyl3FWDYUIG75D6FaTc/TO4FkIJuLaMcoZ0SoJSKuZ001EEeJED8M7zVIOt5RIrMncZN5VeqrGVyEKQR7DEi6ObDWyBzBA+wYnZnHHJo/ourMLCo26uywJ6LHpmuA2VJ/rnXpqo6kZEWmk3I/1uVzLX796gJIkNsx+szv/aS5oTYG4X5cVIlBM99glfH0pDgWbYWkXy0/2//MgPNa01MSj0Xb1xB3PRymC0="
    - secure: "cmgqkEp00jMQ9dqFSKyar/Y43zxlI648cqSJdxcFIXYl+L7+YrEMzLvPH7261rUT1h3I9jwlGm0/ORTnISbnAor17e+S1zBU2c4whKYCHiiXr9ds3fqBe3Z/lt0PKZ1ZAGyXl5SBmp8NfISX5Ff7c8CGHBx/ADdeOsxtl9PIzBLYl4YAZfwjZfNgupqim0NhIJ4z6cxp2wYxtYGoL6Tt9BJxN5cDKeAseo6XZ2z71aYipY9cOVRMUnYaJdippPxriBLQ4WLcAT6cQlDPk56N4i1o3kTXcFTUt6avgPZMEYeP33sL7pb4DTqa7ztte0kDGGLl7pJRyawEUo6GnslVl0Nmu1ju1KQMiD2VjA4BTYTx6tXaMrLZFGGlPK4gNWzxe1iGP3iuWn+TKxbBF2ZbdDyYNJfhTgk/8F4rjTaCOtsqqZcI5lv93hsf5AnWh945oEYFXEWGHL+Z0z1cXNoaP9GOCTbsGDtfuQaIKiQboOEbYTAsetrHLDD/p/amAcZKGHQMQizRRA2CEuJRpAnqM09D6eiHajwFkIl080Ho1XsjNc0erA8iBWTlVS9utDXoSsD80vvfz4uWjHH69aAaiR2tCXZywqYHYYZZ6TjA3qNpovyBvVGu6z5m0ROsX2XfWLvXXC8NDIf5L/Jq33f1FpHsLCHm9b9HLjCjdWyJv2k="
    - secure: "B13YUQO62jvON+TQnUlj5QOzgReASVWwhPTIPfqZ7/4HdJp4/Q4ljDc84uamc5d/twcI26wuyuLstAxKcN41p+arrAojQhwUBX90clAZ6sy7ImPOPwvZeYEX58/JVq1w2rl7sMcKX4vK7Jx8okb6ljktUrT4ROR4ICcIpxNDjF35JjPasLtT/7sY2TdxgzyVJ7SkeYqkca6l6R3BNgnYhw4APIBmvjvLHl+0ifnqgkOv6UMNQnWrVFQTJky7Em4ksx5Wc8Uhux1H7QAF7PgftuergqcauKirM6v6kRSwEH+Zy7yyBVd2tvPj6gOXms7BGBlGKDy7pqmZ3dAxpLbQftPwncfEEo3ggLUIbuI4b7MrAhJt8dgzVBBz+HMRD0RlFy0O2AYCm9rGRlQfynNHR3u76iEwlQSlVVB6kRAOEoTrK2IxjqzNeENhFHSoOl2rO6iQaLQ4synRxJAHhaOUVk1cfvU2OeYkwVy1EUJbCU7wH+cl1r4xpxLhXqE7nDwxTxoWLgZ2NkJAgUouIjhL3I59wP7lFYG4x5gZQxCFmiC31UFOGSE/GRew2Se80BNC+XELP4apF/21Lk0MN+q0lt8cfbaUbfgTlZIhSqwxNH5qAuVo9D12TyOwsAm+bpA0sbnU6580vCXuVJjl+dUmIr2MjOpHwzvKmR2TcZQfUB4="

