language: java

jdk:
 - oraclejdk8

before_install:
- chmod +x ./gradlew
- chmod +x ./cd/before-deploy.sh
- chmod +x ./cd/deploy.sh
 
install: gradle assemble --info

script: gradle test --info

cache:
  directories:
  - "$HOME/.gradle"
after_success:
- ./cd/before-deploy.sh
- ./cd/deploy.sh

env:
  global:
  - secure: eizdd/hlxl+Oz1y0jvjgGxpUZtSlbYIP2M3tkzLMdpTdVzjW1jCY89W94UtVhaHEX9s6d1MGsuEND/UuMy+rr4k7sBKtzC1ieUNEPtxFMZl/hzfQKc16QDyQUnEJ6dydm+7FTwYmNnsaD5wIfvQnt5CgaNQXhajtlQarltzvUotEcYc6FE0BF0no4KSDODc/MFChGlCpJ3NDIMHFEn+pgQHu/gbUzlbmFjlq0j151mms3N2R9vKNAT7zRj70W+TAiwv18+Mh8TV1usDItDLEAxXbE3zGQGRX32BQSv6lCwnLelnroOM9FLDsaDaOI3u2JKPaC/DYNBZaihq0kD5KBx0iFpsg9WP2quZetMiwWfQ0KkHDudTAdqxEKmbvOLWfjFYi5hMMhjnLRVVKlDfeKeGI6T+xtr4ub36GuiRZ2gp4N396Q0QBCmh83MMdEuDIvuFBMD00tm0o3s9L441fvl9BFpJIosEKrBib3iPFJEi0IP2QpoeOULRgVI2qJvn5bMu2IHjuB2OlivOLlfpaQkCjI6+1CPOb+2lMt425qqroLtuE7+Ax2Hto0ejETRGSAxNT/prDIiXEGqfjfPRQUmCx+CwYdh21/MfKkgEKuRJwe932VMNKOlsbF3UF3S/llgCRMQbVju7ewpeRAlorTlr64xdYOUgw66OyJTncxVk=
  - secure: JezHQrNRJksuP9TTEKclB8vpA2eRumIzas2vCwCoH3nqencIMsfoSo0WdJ7yDDhZzRRTs08rES9ispvVAE+lrahz1ArVTv1ChHvJ07HMIG9Vjtz3AbTEXTExS6Kxd+QeYxriGeIqz+hE6ByLczWe9g0gJOJUttJgBSbvVeakpVgWu4QlSEm/sRhfrl6iT9JX7WZLsXaffXCqIrPz6XGplDYVtNo32mwmvNkzvsY/0E3H83pBJlq3J8jtFGYXzfmh/GpNRd4y8fxo/qSeqrPQMUtoT2Vunm7a3tyxBmIkRmnCKTdYU3yAukCAfWeAo2CBjxFXxiN/xMc0POeNuw1OParMGHweC1fht2CFMCs/q0jY7Db2McgXF/jdj5hArLXcUG597QTpoSK4z1PPXKnqxyj2l9/HmdGB+HOHktupGfIFx/Xm+vhigWQKI6YAQGzemUoOJ3UVa5F1hReM8pEghLYqoOGxIP56tX/XPKKk5L4J8I4YEU7J9WgHuss2IFWCdXrBIwuSINI8MhW8CjOXrfFQyEq1KSpdDybHjv7lkRWtcxmorFmfnNTQSY6njcqlVuRa5rc6HphE6PelEs9KzpaNgRuUk5dSfnWGZv8zAXZ08h3MY1xltidHmB5oE0Jbq0y4Q/19jzgIEs9zMVm2nfWQURg0BQ4QkBNoUvd9EwU=
  - secure: l9RRF312arwT/PCwvQAu3qRGNnV4p/7r3IwxQ6PqhzQ27ngJyBf0ZTvF1lEvnsuslBJ5vFUfMYSA5GWY/5BXiYrbh9rBVilPtNgn84J1KLNEL+ENfixXsk75g1PxSJ7TcEwHhzuyWLRQIgpqla/JRQw3N0CTu2B7TaUT0e1eOZrpAJ7InSsBkFR3UYgU7vQ8stdvfpLTR1cECHrJJxv505Pkk5odLzpC/bGL49oxKk7K9KPAceoVYF950RH74HkwpdhqY5xOlknZbGY940N2J8xzh+gb8Xtcye8T5o1zFxtFnBo0esyWbaIg0gtV7TFGX/pZv/WdQLuxvCAlTuuTFQpjDQfTF88zDzbP3U9lccqt/nLugKX9YMZ8QwvamUgJzzPB/kRL7aJJZGIpDG+2ofgjKHcjsVnFtbAhdaaCv7RZuZ0aVMCLqhlb+68ILA5HZlFYujUf26j6+kWdrwMZOd7BCsZjygoTC2jhByKfujcLekC8aycM4Krm+PA5gsmHoybqy6RFMP6axlOrq1Z80dGp1ORbvzmSIVsq1vBxheBcGxu8rP4Nhtx6Cc98S35cZOdZheHNfbzdy9jU6aZuQ1SM0NLy1GUfZEQceSveuonK4UxBnpxqwzXkQPIfk0EW7GYSQVJIcKXz0d1XIcO38mZvbqkOLBwq0GlbUsuvhKo=
  - secure: ByL7tFkJB/ByyE5YiCPfBcHNgXpZgLBVw0nuPJ2VC2h3AD1CSG/tU5Gz/7vGzVRacq0N3c6Z53JrNPfX+9ml4yzx3ijS5WW/YpX9TQe9biKEvQzgPigNEGv2p2XqqvLkn3uQCREB1OLL0r947TCLcTQ+o0t/NB00ivTgKdCAg10kr/VR0gOENgNnaJKFSZiE3cStzLDrrHsCqgtJFy9yM6buFXfxJmfjEneO2NeY6Ej7oR3XQe9fGmb9XVXq+cSHTQ3PeJGX2nCS+Y+5+KIxhf6J0orQAPIdmrRe4cC9DkW2NeNap7ZTL8c8HkN2/cV9m+qBVeKffmo7y4iE/cIdmEmeOKi9NjVpznLpNTec4ONxmWB84Bd8LuPgfsbjdtoE4IFagqsb81dW2XsX4hnbammmpdIjkiy3A85j85lkckGGGlhKusDHWLJ5jTkcFVauisJBf8jLedt76+GV8tZ30ypxKwPDR4rFR4pKg7ncjFi5atJs/x10Ti8IUXlkaBXDCgFWvmnuMkr4U/CVt7xzhAu7zzGfT1GFmb75JLzNfCnHCYUvpFiyXhh1drncWgVNpezQVjsQBe82NMzkxnuvFwXQWHLOMCmqycXofp7tuG2DSy8IS0SCDBd4zSCbFq5wux2f2tQk+OgzkvwayHE0AWY7m0N8nDThXj7RX5DKKcI=
